site_name: '&nbsp;'
site_url: https://accelerate.tpau.group/
repo_url: https://github.com/T-Pau/Accelerate
copyright: ©2024 Dieter Baron
extra:
  generator: false
plugins:
  - extra-sass
  - privacy
  - search
theme:
  name: material
  custom_dir: overrides
  font: false
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github   
  palette:
    primary: custom
  features:
    - navigation.indexes 
    - toc.integrate 
nav:
  - index.md
  - Documentation: 
    - Documentation/index.md
    - Documentation/Introduction.md
    - Documentation/Assembler-Source-File.md
    - Documentation/Expressions.md
    - Documentation/Target-Definition.md
    - Documentation/CPU-Definition.md
  - Examples:
    - Examples/index.md
    - Examples/Hello-World-C64.md
  - License.md
  - Repository: 'https://github.com/T-Pau/Accelerate/'
